package com.example.talkies.view.Util

import com.example.talkies.data.model.CountryInfo

object CountryData {
    val countries = listOf(
        CountryInfo("Afghanistan", "+93", 9),
        CountryInfo("Albania", "+355", 9),
        CountryInfo("Algeria", "+213", 9),
        CountryInfo("Andorra", "+376", 6),
        CountryInfo("Angola", "+244", 9),
        CountryInfo("Antigua and Barbuda", "+1", 10),
        CountryInfo("Argentina", "+54", 10),
        CountryInfo("Armenia", "+374", 8),
        CountryInfo("Australia", "+61", 9),
        CountryInfo("Austria", "+43", 10),
        CountryInfo("Azerbaijan", "+994", 9),
        CountryInfo("Bahamas", "+1", 10),
        CountryInfo("Bahrain", "+973", 8),
        CountryInfo("Bangladesh", "+880", 10),
        CountryInfo("Barbados", "+1", 10),
        CountryInfo("Belarus", "+375", 9),
        CountryInfo("Belgium", "+32", 9),
        CountryInfo("Belize", "+501", 7),
        CountryInfo("Benin", "+229", 8),
        CountryInfo("Bhutan", "+975", 8),
        CountryInfo("Bolivia", "+591", 8),
        CountryInfo("Bosnia and Herzegovina", "+387", 8),
        CountryInfo("Botswana", "+267", 7),
        CountryInfo("Brazil", "+55", 11),
        CountryInfo("Brunei", "+673", 7),
        CountryInfo("Bulgaria", "+359", 9),
        CountryInfo("Burkina Faso", "+226", 8),
        CountryInfo("Burundi", "+257", 8),
        CountryInfo("Côte d'Ivoire", "+225", 8),
        CountryInfo("Cabo Verde", "+238", 7),
        CountryInfo("Cambodia", "+855", 9),
        CountryInfo("Cameroon", "+237", 9),
        CountryInfo("Canada", "+1", 10),
        CountryInfo("Central African Republic", "+236", 8),
        CountryInfo("Chad", "+235", 8),
        CountryInfo("Chile", "+56", 9),
        CountryInfo("China", "+86", 11),
        CountryInfo("Colombia", "+57", 10),
        CountryInfo("Comoros", "+269", 7),
        CountryInfo("Congo (Congo-Brazzaville)", "+242", 9),
        CountryInfo("Costa Rica", "+506", 8),
        CountryInfo("Croatia", "+385", 9),
        CountryInfo("Cuba", "+53", 8),
        CountryInfo("Cyprus", "+357", 8),
        CountryInfo("Czechia (Czech Republic)", "+420", 9),
        CountryInfo("Denmark", "+45", 8),
        CountryInfo("Djibouti", "+253", 8),
        CountryInfo("Dominica", "+1", 10),
        CountryInfo("Dominican Republic", "+1", 10),
        CountryInfo("Ecuador", "+593", 9),
        CountryInfo("Egypt", "+20", 10),
        CountryInfo("El Salvador", "+503", 8),
        CountryInfo("Equatorial Guinea", "+240", 9),
        CountryInfo("Eritrea", "+291", 7),
        CountryInfo("Estonia", "+372", 8),
        CountryInfo("Eswatini", "+268", 8),
        CountryInfo("Ethiopia", "+251", 9),
        CountryInfo("Fiji", "+679", 7),
        CountryInfo("Finland", "+358", 9),
        CountryInfo("France", "+33", 9),
        CountryInfo("Gabon", "+241", 8),
        CountryInfo("Gambia", "+220", 7),
        CountryInfo("Georgia", "+995", 9),
        CountryInfo("Germany", "+49", 10),
        CountryInfo("Ghana", "+233", 9),
        CountryInfo("Greece", "+30", 10),
        CountryInfo("Grenada", "+1", 10),
        CountryInfo("Guatemala", "+502", 8),
        CountryInfo("Guinea", "+224", 9),
        CountryInfo("Guinea-Bissau", "+245", 7),
        CountryInfo("Guyana", "+592", 7),
        CountryInfo("Haiti", "+509", 8),
        CountryInfo("Holy See", "+379", 10),
        CountryInfo("Honduras", "+504", 8),
        CountryInfo("Hungary", "+36", 9),
        CountryInfo("Iceland", "+354", 7),
        CountryInfo("India", "+91", 10),
        CountryInfo("Indonesia", "+62", 10),
        CountryInfo("Iran", "+98", 10),
        CountryInfo("Iraq", "+964", 10),
        CountryInfo("Ireland", "+353", 9),
        CountryInfo("Israel", "+972", 9),
        CountryInfo("Italy", "+39", 10),
        CountryInfo("Jamaica", "+1", 10),
        CountryInfo("Japan", "+81", 10),
        CountryInfo("Jordan", "+962", 9),
        CountryInfo("Kazakhstan", "+7", 10),
        CountryInfo("Kenya", "+254", 9),
        CountryInfo("Kiribati", "+686", 8),
        CountryInfo("Korea, North", "+850", 10),
        CountryInfo("Korea, South", "+82", 10),
        CountryInfo("Kosovo", "+383", 8),
        CountryInfo("Kuwait", "+965", 8),
        CountryInfo("Kyrgyzstan", "+996", 9),
        CountryInfo("Laos", "+856", 10),
        CountryInfo("Latvia", "+371", 8),
        CountryInfo("Lebanon", "+961", 8),
        CountryInfo("Lesotho", "+266", 8),
        CountryInfo("Liberia", "+231", 8),
        CountryInfo("Libya", "+218", 9),
        CountryInfo("Liechtenstein", "+423", 7),
        CountryInfo("Lithuania", "+370", 8),
        CountryInfo("Luxembourg", "+352", 9),
        CountryInfo("Madagascar", "+261", 9),
        CountryInfo("Malawi", "+265", 9),
        CountryInfo("Malaysia", "+60", 9),
        CountryInfo("Maldives", "+960", 7),
        CountryInfo("Mali", "+223", 8),
        CountryInfo("Malta", "+356", 8),
        CountryInfo("Marshall Islands", "+692", 7),
        CountryInfo("Mauritania", "+222", 8),
        CountryInfo("Mauritius", "+230", 8),
        CountryInfo("Mexico", "+52", 10),
        CountryInfo("Micronesia", "+691", 7),
        CountryInfo("Moldova", "+373", 8),
        CountryInfo("Monaco", "+377", 9),
        CountryInfo("Mongolia", "+976", 8),
        CountryInfo("Montenegro", "+382", 8),
        CountryInfo("Morocco", "+212", 9),
        CountryInfo("Mozambique", "+258", 9),
        CountryInfo("Myanmar (Burma)", "+95", 9),
        CountryInfo("Namibia", "+264", 9),
        CountryInfo("Nauru", "+674", 7),
        CountryInfo("Nepal", "+977", 10),
        CountryInfo("Netherlands", "+31", 9),
        CountryInfo("New Zealand", "+64", 9),
        CountryInfo("Nicaragua", "+505", 8),
        CountryInfo("Niger", "+227", 8),
        CountryInfo("Nigeria", "+234", 10),
        CountryInfo("North Macedonia", "+389", 8),
        CountryInfo("Norway", "+47", 8),
        CountryInfo("Oman", "+968", 8),
        CountryInfo("Pakistan", "+92", 10),
        CountryInfo("Palau", "+680", 7),
        CountryInfo("Palestine State", "+970", 9),
        CountryInfo("Panama", "+507", 8),
        CountryInfo("Papua New Guinea", "+675", 8),
        CountryInfo("Paraguay", "+595", 9),
        CountryInfo("Peru", "+51", 9),
        CountryInfo("Philippines", "+63", 10),
        CountryInfo("Poland", "+48", 9),
        CountryInfo("Portugal", "+351", 9),
        CountryInfo("Qatar", "+974", 8),
        CountryInfo("Romania", "+40", 9),
        CountryInfo("Russia", "+7", 10),
        CountryInfo("Rwanda", "+250", 9),
        CountryInfo("Saint Kitts and Nevis", "+1", 10),
        CountryInfo("Saint Lucia", "+1", 10),
        CountryInfo("Saint Vincent and the Grenadines", "+1", 10),
        CountryInfo("Samoa", "+685", 7),
        CountryInfo("San Marino", "+378", 10),
        CountryInfo("Sao Tome and Principe", "+239", 7),
        CountryInfo("Saudi Arabia", "+966", 9),
        CountryInfo("Senegal", "+221", 9),
        CountryInfo("Serbia", "+381", 9),
        CountryInfo("Seychelles", "+248", 7),
        CountryInfo("Sierra Leone", "+232", 8),
        CountryInfo("Singapore", "+65", 8),
        CountryInfo("Slovakia", "+421", 9),
        CountryInfo("Slovenia", "+386", 8),
        CountryInfo("Solomon Islands", "+677", 7),
        CountryInfo("Somalia", "+252", 8),
        CountryInfo("South Africa", "+27", 9),
        CountryInfo("South Sudan", "+211", 9),
        CountryInfo("Spain", "+34", 9),
        CountryInfo("Sri Lanka", "+94", 9),
        CountryInfo("Sudan", "+249", 9),
        CountryInfo("Suriname", "+597", 7),
        CountryInfo("Sweden", "+46", 9),
        CountryInfo("Switzerland", "+41", 9),
        CountryInfo("Syria", "+963", 9),
        CountryInfo("Tajikistan", "+992", 9),
        CountryInfo("Tanzania", "+255", 9),
        CountryInfo("Thailand", "+66", 9),
        CountryInfo("Timor-Leste", "+670", 8),
        CountryInfo("Togo", "+228", 8),
        CountryInfo("Tonga", "+676", 7),
        CountryInfo("Trinidad and Tobago", "+1", 10),
        CountryInfo("Tunisia", "+216", 8),
        CountryInfo("Turkey", "+90", 10),
        CountryInfo("Turkmenistan", "+993", 8),
        CountryInfo("Tuvalu", "+688", 6),
        CountryInfo("Uganda", "+256", 9),
        CountryInfo("Ukraine", "+380", 9),
        CountryInfo("United Arab Emirates", "+971", 9),
        CountryInfo("United Kingdom", "+44", 10),
        CountryInfo("United States of America", "+1", 10),
        CountryInfo("Uruguay", "+598", 8),
        CountryInfo("Uzbekistan", "+998", 9),
        CountryInfo("Vanuatu", "+678", 7),
        CountryInfo("Venezuela", "+58", 10),
        CountryInfo("Vietnam", "+84", 10),
        CountryInfo("Yemen", "+967", 9),
        CountryInfo("Zambia", "+260", 9),
        CountryInfo("Zimbabwe", "+263", 9)
    )
}